#!/bin/sh /etc/rc.common

NAME=piratebox
START=80
STOP=20
EXTRA_COMMANDS="init update nodns"
EXTRA_HELP="	init	PirateBoxify a fresh USB disk
	update	Update PirateBox files on USB disk
	nodns	Disable local DNS redirection through dnsmasq"

# include PirateBox shared functionality
. /etc/piratebox.common

nodns() {
  pb_nodns
}

init() {
  pb_init
}

update() {
  pb_update
}

start() {
  pb_mount usb
  # init if we have a fresh USB disk
  if [ ! -d "$pb_usbdir" ]
  then
    pb_init
    pb_update
  fi
  # be silent
  pb_start &>/dev/null
}

stop() {
  pb_stop
}

