#!/bin/sh /etc/rc.common

NAME=piratebox
START=80
STOP=20
EXTRA_COMMANDS="setup init update nodns"
EXTRA_HELP="	setup	Activate current USB and network configuration
	init	Mount USB, and PirateBoxify a fresh USB disk
	update	Update PirateBox files on USB disk
	nodns	Disable local DNS redirection through dnsmasq"

# include PirateBox shared functionality
. /etc/piratebox.common

setup() {
  pb_usbsetup
  pb_netconfig
}

init() {
  pb_init
}

update() {
  pb_update
}

nodns() {
  pb_nodns
}

start() {
  pb_mount usb
  # init if we have a fresh USB disk
  if [ ! -d "$pb_usbdir" ]
  then
    pb_init
    pb_update
  fi
  # be silent
  pb_start &>/dev/null
}

stop() {
  pb_stop
}

