#!/bin/ash

# include PirateBox shared functionality
. /etc/piratebox.common

# wait for USB disk to show up
pb_usbwait

# check if root password is not set yet
if grep '^root:!:' /etc/passwd >/dev/null
then
  echo "Please set a decent root password..."
  while ! passwd
  do
    echo "Try again!"
  done
  echo "Next time you log in, you must use ssh."
fi

# disable web interface, start PirateBox instead
/etc/init.d/uhttpd stop
/etc/init.d/uhttpd disable
/etc/init.d/luci_fixtime stop
/etc/init.d/luci_fixtime disable
/etc/init.d/luci_dhcp_migrate stop
/etc/init.d/luci_dhcp_migrate disable
/etc/init.d/piratebox enable

# configure USB, network
/etc/init.d/piratebox setup

# prepare USB partition and install PirateBox
/etc/init.d/piratebox init
/etc/init.d/piratebox update

# activate config changes
/etc/init.d/firewall restart
/etc/init.d/dnsmasq restart
wifi

# start PirateBox service
/etc/init.d/piratebox start

# give some user feedback
echo
echo "PirateBox wireless SSID: $pb_wireless_ssid"
echo "PirateBox DNS and hostname: $pb_hostname"
echo "PirateBox LAN IP address: $pb_ip"
echo "PirateBox shared directory: $pb_share"
echo
echo "Setup complete, PirateBox started."
echo "You can remove the WAN connection now."

