#!/bin/ash

. /etc/piratebox.common

/etc/init.d/luci_fixtime enable
/etc/init.d/luci_dhcp_migrate enable
/etc/init.d/uhttpd enable
/etc/init.d/piratebox disable

/etc/init.d/piratebox stop
/etc/init.d/piratebox nodns

# undo configuration
echo "Resetting OpenWRT config to factory state..."
pb_undoconfig
echo "Please reboot for changes to take effect."

